### ISSUE TITLE
Bench: Async benchmark tests run very slow

### ISSUE THREAD

**Issue by danielkon96** [uber-web/probe.gl#204]
**Background:** I'm running a benchmark test where I created an async function with a 5 second delay. The benchmark took 178s on average to run. If I lower the delay to 1 second, the benchmark took 30 seconds, when I increase the delay to 10 seconds, the benchmark took 318s. 

**Question:** I'm curious why a 5 second function took 3 minutes to run, or a 10 second function took 5+ minutes to run. Is this a bug or is Bench intended to take this long?

**Note:** I noticed after further research that `runBenchTestForMinimumTimeAsync` has a multiplier of 10 by default on line 306 in `bench.ts` and it cannot be changed. Is there anything that can be done to be able to control that?

**Comment by ibgreen** [comment]
Without having time to look in detail:

probe runs test cases multiple times to get an average score. 

- For async tests, there should be a flag to run things in parallel to test total throughput, rather than in sequence. 

The 10x multiplier may be related to a wish to make the results less flaky (on a mac, timings typically vary ~10-20% between runs due to OS scheduling etc, which makes it hard to make precise decisions based on timings).

However, faster but a bit less precise timings are still preferred in many situations.

**Comment by danielkon96** [comment]
@ibgreen Do you know where that flag is to turn tests into parallel? It is not found in the test parameters (priority, id, func1, func2).

**Comment by ibgreen** [comment]
I think it is `_throughput`, it was used in loaders.gl

**Comment by danielkon96** [comment]
That worked! Thanks @ibgreen.
